modLoader="javafml"
loaderVersion="[45,)"
license="MIT"

[[mods]]
modId="minearchive"
version="1.0"
displayName="MineArchive"
main="com.anthonyhilyard.minearchive.MineArchiveMod"
displayURL="https://modrinth.com/mod/minearchive"
updateJSONURL="https://modrinth.com/mod/minearchive"
logoFile="icon.png"
authors="Creator:Transit Station Laodeng        Chat in the official group:910583060"
description="Minecraft x Blue Archive."

[[mods.mixinConfigs]]
config="minearchive.mixins.json"

[[dependencies.minearchive]]
modId="forge"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"


[[dependencies.minearchive]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,]"
ordering="NONE"
side="BOTH"